spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kotlin-springboot
    username: postgres
    password: kotlin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false